# Generated by Django 4.2.5 on 2024-06-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='status',
        ),
    ]
