# Generated by Django 4.2.5 on 2024-06-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_remove_notif_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notif',
            table='notif_notif',
        ),
    ]
