# Generated by Django 4.2.5 on 2024-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0005_notifications_org_notifications_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='org',
        ),
        migrations.AddField(
            model_name='notifications',
            name='target_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
