version: '3.9'

services:

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres: