version: '3.9'

services:
  db:
    image: sqlite:latest
    volumes:
      - ./sqlite_data:/code/

  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  sqlite_data: