# Generated by Django 4.2.5 on 2024-05-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_organization_subscription_and_more'),
        ('marketplace', '0002_order_booked_at_order_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipments', to='marketplace.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_equipment', to='authorization.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='marketplace.ordercategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_orders', to='authorization.userprofile'),
        ),
    ]
