# Generated by Django 4.2.5 on 2024-05-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_service_author_org_remove_service_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='service',
            name='email',
        ),
    ]
