# Generated by Django 4.2.5 on 2024-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_equipment_email_remove_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('Ruble', 'Ruble'), ('USD', 'USD'), ('Euro', 'Euro')], default='Som', max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('Ruble', 'Ruble'), ('USD', 'USD'), ('Euro', 'Euro')], default='Som', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('Ruble', 'Ruble'), ('USD', 'USD'), ('Euro', 'Euro')], default='Som', max_length=10),
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ManyToManyField(related_name='orders', to='marketplace.size'),
        ),
    ]
