# Generated by Django 4.2.5 on 2024-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_service_category_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
