# Generated by Django 4.2.5 on 2024-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_equipment_email_alter_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='sold',
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
