# Generated by Django 4.2.5 on 2024-06-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_userprofile_device_token'),
        ('marketplace', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='org_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to='authorization.organization'),
        ),
    ]
