# Generated by Django 4.2.5 on 2024-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_order_org_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
