# Generated by Django 4.2.5 on 2024-05-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_confirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_org',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_member', to='authorization.organization'),
        ),
    ]
