# Generated by Django 4.2.5 on 2024-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_userprofile_current_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subscription',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_type',
            field=models.CharField(choices=[('Тест-драйв', 'Тест-драйв'), ('Базовый', 'Базовый'), ('Премиум', 'Премиум'), ('Нет подписки', 'Нет подписки')], default='Нет подписки', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=7, null=True),
        ),
    ]
