# Generated by Django 4.2.5 on 2024-05-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_organization_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_org',
        ),
        migrations.AlterField(
            model_name='organization',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='founder_organizations', to='authorization.userprofile', verbose_name='founder'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_organizations', to='authorization.userprofile', verbose_name='owner'),
        ),
    ]
