# Generated by Django 4.2.5 on 2024-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_remove_userprofile_current_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
