# Generated by Django 4.2.5 on 2024-05-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_organization_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='smarttale/organization'),
        ),
    ]
