# Generated by Django 4.2.5 on 2024-06-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
