# Generated by Django 4.2.5 on 2024-05-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('authorization', '0006_alter_organization_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('flag_create_jobtitle', models.BooleanField(default=False)),
                ('flag_remove_jobtitle', models.BooleanField(default=False)),
                ('flag_update_access', models.BooleanField(default=False)),
                ('flag_add_employee', models.BooleanField(default=False)),
                ('flag_update_order', models.BooleanField(default=False)),
                ('flag_delete_order', models.BooleanField(default=False)),
                ('flag_remove_employee', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authorization.organization', verbose_name='org')),
            ],
            options={
                'unique_together': {('org', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Авторизован', 'Авторизован'), ('Ожидает подтверждения', 'Ожидает подтверждения')], default='Авторизован', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jt_employees', to='monitoring.jobtitle', verbose_name='job_title')),
                ('order', models.ManyToManyField(related_name='workers', to='marketplace.order', verbose_name='order')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='authorization.organization', verbose_name='org')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_org', to='authorization.userprofile', verbose_name='user')),
            ],
        ),
    ]
