# Generated by Django 4.2.5 on 2024-05-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_organization_title'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_orgs', to='authorization.userprofile', verbose_name='user'),
        ),
    ]
