# Generated by Django 4.2.5 on 2024-05-26 21:31

import autoslug.fields
from django.db import migrations
import monitoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='job-title', editable=False, populate_from='title', unique = True),
        ),
    ]
