# Generated by Django 4.2.5 on 2024-06-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
