# Generated by Django 4.2.5 on 2024-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_remove_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='flag_change_employee_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='flag_create_vacancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='flag_employee_detail_access',
            field=models.BooleanField(default=False),
        ),
    ]
