# Generated by Django 4.2.5 on 2024-05-19 19:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0006_alter_organization_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='job_title', unique=True)),
                ('schedule', models.CharField(choices=[('Полный день', 'Полный день'), ('Неполный день', 'Неполный день'), ('Частичная занятость', 'Частичная занятость'), ('Гибкий график', 'Гибкий график'), ('Удаленно', 'Удаленно')], default='Полный день', max_length=60)),
                ('location', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Каракол', 'Каракол'), ('Нарын', 'Нарын'), ('Ош', 'Ош'), ('Джалал-Абад', 'Джалал-Абад'), ('Баткен', 'Баткен'), ('Талас', 'Талас')], default='Бишкек', max_length=30)),
                ('description', models.TextField(max_length=1200, null=True)),
                ('experience', models.CharField(choices=[('Без опыта', 'Без опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 лет до 6 лет', 'От 3 лет до 6 лет'), ('Более 6 лет', 'Более 6 лет')], default='Без опыта', max_length=30)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('Сом', 'Сом'), ('USD', 'USD'), ('Рубль', 'Рубль')], default='Сом', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_vacancy', to='authorization.organization')),
                ('user_applicants', models.ManyToManyField(blank=True, related_name='applied_vacancy', to='authorization.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='job_title', unique=True)),
                ('location', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Каракол', 'Каракол'), ('Нарын', 'Нарын'), ('Ош', 'Ош'), ('Джалал-Абад', 'Джалал-Абад'), ('Баткен', 'Баткен'), ('Талас', 'Талас')], default='Бишкек', max_length=30, null=True)),
                ('schedule', models.CharField(choices=[('Полный день', 'Полный день'), ('Неполный день', 'Неполный день'), ('Частичная занятость', 'Частичная занятость'), ('Гибкий график', 'Гибкий график'), ('Удаленно', 'Удаленно')], default='Полный день', max_length=60)),
                ('experience', models.CharField(choices=[('Без опыта', 'Без опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 лет до 6 лет', 'От 3 лет до 6 лет'), ('Более 6 лет', 'Более 6 лет')], default='Без опыта', max_length=30)),
                ('about_me', models.TextField(max_length=1000, null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('Сом', 'Сом'), ('USD', 'USD'), ('Рубль', 'Рубль')], default='Сом', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_resume', to='authorization.userprofile')),
            ],
        ),
    ]
