# Generated by Django 4.2.5 on 2024-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('Без опыта', 'Без опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 лет до 6 лет', 'От 3 лет до 6 лет'), ('Более 6 лет', 'Более 6 лет'), ('Не имеет значение', 'Не имеет значение')], default='Без опыта', max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('Без опыта', 'Без опыта'), ('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('От 3 лет до 6 лет', 'От 3 лет до 6 лет'), ('Более 6 лет', 'Более 6 лет'), ('Не имеет значение', 'Не имеет значение')], default='Без опыта', max_length=30),
        ),
    ]
