# Generated by Django 4.2.5 on 2024-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_resume_experience_alter_vacancy_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('USD', 'USD'), ('Ruble', 'Ruble'), ('Euro', 'Euro')], default='Сом', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('USD', 'USD'), ('Ruble', 'Ruble'), ('Euro', 'Euro')], default='Сом', max_length=15),
        ),
    ]
