# Generated by Django 4.2.5 on 2024-05-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_organization_logo'),
        ('job', '0003_alter_resume_currency_alter_vacancy_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_resume', to='authorization.userprofile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('USD', 'USD'), ('Ruble', 'Ruble'), ('Euro', 'Euro')], default='Som', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('Som', 'Som'), ('USD', 'USD'), ('Ruble', 'Ruble'), ('Euro', 'Euro')], default='Som', max_length=15),
        ),
    ]
