# Generated by Django 4.2.5 on 2024-05-31 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_organization_logo'),
        ('job', '0004_resume_hide_vacancy_hide_alter_resume_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.userprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.vacancy')),
            ],
        ),
    ]
