# Generated by Django 4.2.5 on 2024-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_vacancyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
