# Generated by Django 4.2.5 on 2024-06-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_userprofile_device_token'),
        ('job', '0006_resume_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyresponse',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_response', to='authorization.userprofile'),
        ),
    ]
